# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10d3c6305667a54c2b4c6049e559371ff75b8abbcc17e4dd636a806c976ea619ffa38865cd848f7281fd8fc14508bb4328fe783696ee890bbbe21ba58ed69c64

test:
  secret_key_base: 30b5ef3940e90e5e980e51cb3e41e6e89f37370e92910cdf87a787541fcc2d86dcc3fcc5719cd6d239ee67738e8059f6b7b9db29a1a49c7b60ecff5a28293b0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
